/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ramon.proyectofinal.utilidades;

import static com.ramon.proyectofinal.Windows.currentDirectory;
import static com.ramon.proyectofinal.modelos.DoctorDAO.doctorName;

import com.ramon.proyectofinal.modelos.citas;
import com.ramon.proyectofinal.modelos.citasDAO;

import avisos.alert;
import avisos.success;

import com.ramon.proyectofinal.LoginWindows;


import javax.swing.table.DefaultTableModel;

/**
 *
 * @author el_an
 */
public class DoctorWindows extends javax.swing.JFrame {

    /**
     * Creates new form DoctorWindows
     */
    public DoctorWindows() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upperPanel = new javax.swing.JPanel();
        powerButton = new javax.swing.JLabel();
        logoIcon = new javax.swing.JLabel();
        titleCentral = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        titleMid = new javax.swing.JLabel();
        addLB = new javax.swing.JLabel();
        listLB = new javax.swing.JLabel();
        refreshLB = new javax.swing.JLabel();
        removeLB = new javax.swing.JLabel();
        reportLB = new javax.swing.JLabel();
        addPanel = new javax.swing.JPanel();
        titleMid1 = new javax.swing.JLabel();
        dateLB = new javax.swing.JLabel();
        timeLB = new javax.swing.JLabel();
        whereLB = new javax.swing.JLabel();
        dateTF = new javax.swing.JTextField();
        timeTF = new javax.swing.JTextField();
        whereTF = new javax.swing.JTextField();
        save = new javax.swing.JLabel();
        listPanel = new javax.swing.JPanel();
        titleMid2 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        reload = new javax.swing.JLabel();
        refreshPanel = new javax.swing.JPanel();
        titleMid3 = new javax.swing.JLabel();
        dateLB1 = new javax.swing.JLabel();
        timeLB1 = new javax.swing.JLabel();
        whereLB1 = new javax.swing.JLabel();
        dateTF1 = new javax.swing.JTextField();
        timeTF1 = new javax.swing.JTextField();
        whereTF1 = new javax.swing.JTextField();
        save1 = new javax.swing.JLabel();
        idLB = new javax.swing.JLabel();
        idSP = new javax.swing.JSpinner();
        removePanel = new javax.swing.JPanel();
        titleMid4 = new javax.swing.JLabel();
        save2 = new javax.swing.JLabel();
        idLB1 = new javax.swing.JLabel();
        idSP1 = new javax.swing.JSpinner();
        iconFrame =new javax.swing.ImageIcon(currentDirectory+"icons8_hospital_sign_55px_1.png");

        setIconImage(iconFrame.getImage());
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(50, 100));
        setLocationByPlatform(true);
        setUndecorated(true);

        upperPanel.setBackground(new java.awt.Color(51, 255, 204));
        upperPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        powerButton.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_shutdown_48px.png"));
        powerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        powerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setVisible(false);
                dispose(); 
                new LoginWindows().setVisible(true);
            }
        });

        logoIcon.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_hospital_48px.png")); // NOI18N

        titleCentral.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleCentral.setText("  Consultorio del Doctor "+doctorName);

        minimizeButton.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_minimize_window_55px.png")); // NOI18N
        minimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setState(DoctorWindows.ICONIFIED);

            }
        });

        final javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(minimizeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(powerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(upperPanelLayout.createSequentialGroup()
                        .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(powerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minimizeButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        centerPanel.setBackground(new java.awt.Color(153, 255, 153));
        centerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        centerPanel.setLayout(new java.awt.CardLayout());

        panelMenu.setBackground(new java.awt.Color(153, 255, 153));

        titleMid.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleMid.setForeground(new java.awt.Color(255, 255, 255));
        titleMid.setText("Que desea hacer?");
        titleMid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        addLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        addLB.setText("Agregar una cita");
        addLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        //action event
        addLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenu.setVisible(false);
                addPanel.setVisible(true);

            }
        });
        

        listLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        listLB.setText("Listado de citas");
        listLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                //action event
                listLB.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        panelMenu.setVisible(false);
                        listPanel.setVisible(true);

        
                    }
                });

        refreshLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        refreshLB.setText("Actualizar cita");
        refreshLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                //action event
                refreshLB.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        panelMenu.setVisible(false);
                        refreshPanel.setVisible(true);
        
                    }
                });

        removeLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        removeLB.setText("Borrar cita");
        removeLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                //action event
                removeLB.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        panelMenu.setVisible(false);
                        removePanel.setVisible(true);
        
                    }
                });

        reportLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        reportLB.setForeground(new java.awt.Color(255, 255, 255));
        reportLB.setText("Reporte de Pacientes");
        reportLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                        //action event
                        reportLB.addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(java.awt.event.MouseEvent evt) {
                                setVisible(false);
                                dispose(); 
                                new ReportDoctor().setVisible(true);
                
                            }
                        });

        final javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addLB))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(listLB)))
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(removeLB)
                        .addGap(72, 72, 72))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(refreshLB)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addComponent(titleMid)
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addComponent(reportLB)
                        .addGap(219, 219, 219))))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(titleMid)
                .addGap(47, 47, 47)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLB)
                    .addComponent(refreshLB))
                .addGap(31, 31, 31)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listLB)
                    .addComponent(removeLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(reportLB)
                .addGap(35, 35, 35))
        );

        centerPanel.add(panelMenu, "card2");

        addPanel.setBackground(new java.awt.Color(153, 255, 153));

        titleMid1.setFont(new java.awt.Font("Arial", 1, 24)); 
        titleMid1.setForeground(new java.awt.Color(255, 255, 255));
        titleMid1.setText("Agregando una Cita");
        titleMid1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        dateLB.setFont(new java.awt.Font("Arial", 1, 24)); 
        dateLB.setText("Fecha:");
        dateLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        timeLB.setFont(new java.awt.Font("Arial", 1, 24)); 
        timeLB.setText("Hora:");
        timeLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        whereLB.setFont(new java.awt.Font("Arial", 1, 24)); 
        whereLB.setText("Lugar:");
        whereLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        save.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_save_48px_1.png")); 
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                //action event
                save.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {

                        citas datos= new citas();
                        
                        datos.setDate(dateTF.getText());
                        datos.setTime(timeTF.getText());
                        datos.setWhere(whereTF.getText());

                        if(datos.getDate().isEmpty()||datos.getTime().isEmpty()||datos.getWhere().isEmpty()){
                            new alert("isEmpty").setVisible(true);

                        }

                        else{
                            citasDAO.crearDoctorCitaDB(datos);
                            addPanel.setVisible(false);

                            new success("save").setVisible(true);
                        }
        
                    }
                });

        final javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(titleMid1)
                .addGap(246, 246, 246))
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(whereLB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(whereTF))
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(dateLB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(timeLB)
                                .addGap(18, 18, 18)
                                .addComponent(timeTF))))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(save)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(titleMid1)
                .addGap(37, 37, 37)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLB)
                    .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLB)
                    .addComponent(timeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(whereLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(whereTF))
                .addGap(18, 18, 18)
                .addComponent(save)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        centerPanel.add(addPanel, "card2");

        listPanel.setBackground(new java.awt.Color(153, 255, 153));

        titleMid2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleMid2.setForeground(new java.awt.Color(255, 255, 255));
        titleMid2.setText("Listado de citas");
        titleMid2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        back.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_back_48px.png")); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                        //action event
                        back.addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(java.awt.event.MouseEvent evt) {
                                listPanel.setVisible(false);
                                panelMenu.setVisible(true);
                
                            }
                        });

        //table an rows
        String[]columns= {"id_cita", "Fecha", "Hora", "Lugar","id_doctor","created","modified"};
        DefaultTableModel modelo= new DefaultTableModel(null,columns);
        jTable1.setModel(modelo);
        citasDAO.listarDoctorCitasDB(modelo,"doctor");
        
        jScrollPane1.setViewportView(jTable1);

        reload.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_process_48px_1.png")); // NOI18N
        reload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                                //action event
                                reload.addMouseListener(new java.awt.event.MouseAdapter() {
                                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                                        DefaultTableModel modelo= new DefaultTableModel(null,columns);
                                        jTable1.setModel(modelo);
                                        citasDAO.listarDoctorCitasDB(modelo,"doctor");
                        
                                    }
                                });

        final javax.swing.GroupLayout listPanelLayout = new javax.swing.GroupLayout(listPanel);
        listPanel.setLayout(listPanelLayout);
        listPanelLayout.setHorizontalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPanelLayout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listPanelLayout.createSequentialGroup()
                        .addComponent(titleMid2)
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listPanelLayout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(40, 40, 40)
                        .addComponent(reload)
                        .addGap(277, 277, 277))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        listPanelLayout.setVerticalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(titleMid2)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(back)
                    .addComponent(reload))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        centerPanel.add(listPanel, "card2");

        refreshPanel.setBackground(new java.awt.Color(153, 255, 153));

        refreshPanel.setBackground(new java.awt.Color(153, 255, 153));

        titleMid3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleMid3.setForeground(new java.awt.Color(255, 255, 255));
        titleMid3.setText("Actualizando Cita");
        titleMid3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        dateLB1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        dateLB1.setText("Fecha:");
        dateLB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        timeLB1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        timeLB1.setText("Hora:");
        timeLB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        whereLB1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        whereLB1.setText("Lugar:");
        whereLB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        save1.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_save_48px_1.png")); // NOI18N
        save1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                                        //action event
                                        save1.addMouseListener(new java.awt.event.MouseAdapter() {
                                            public void mouseClicked(java.awt.event.MouseEvent evt) {
                                                citas datos= new citas();
                        
                                                datos.setDate(dateTF1.getText());
                                                datos.setTime(timeTF1.getText());
                                                datos.setWhere(whereTF1.getText());
                                                int x=(Integer)idSP.getValue();

                        
                                                if(datos.getDate().isEmpty()||datos.getTime().isEmpty()||datos.getWhere().isEmpty()){
                                                    new alert("isEmpty").setVisible(true);
                        
                                                }
                        
                                                else{
                                                    refreshPanel.setVisible(false);
                                                    citasDAO.actualizarDoctorCitaDB(datos,x);
                        
                                                }
                                            }
                                        });

        idLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        idLB.setText("ID:");

        final javax.swing.GroupLayout refreshPanelLayout = new javax.swing.GroupLayout(refreshPanel);
        refreshPanel.setLayout(refreshPanelLayout);
        refreshPanelLayout.setHorizontalGroup(
            refreshPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(refreshPanelLayout.createSequentialGroup()
                .addGroup(refreshPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(refreshPanelLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(refreshPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(refreshPanelLayout.createSequentialGroup()
                                .addComponent(whereLB1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(whereTF1))
                            .addGroup(refreshPanelLayout.createSequentialGroup()
                                .addComponent(dateLB1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(refreshPanelLayout.createSequentialGroup()
                                .addComponent(timeLB1)
                                .addGap(18, 18, 18)
                                .addComponent(timeTF1))))
                    .addGroup(refreshPanelLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(save1))
                    .addGroup(refreshPanelLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(idLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idSP, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(refreshPanelLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(titleMid3)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        refreshPanelLayout.setVerticalGroup(
            refreshPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(refreshPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(titleMid3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(refreshPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idSP))
                .addGap(18, 18, 18)
                .addGroup(refreshPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLB1)
                    .addComponent(dateTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(refreshPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLB1)
                    .addComponent(timeTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(refreshPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(whereLB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(whereTF1))
                .addGap(18, 18, 18)
                .addComponent(save1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        centerPanel.add(refreshPanel, "card2");

        removePanel.setBackground(new java.awt.Color(153, 255, 153));

        titleMid4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleMid4.setForeground(new java.awt.Color(255, 255, 255));
        titleMid4.setText("Borrar cita");
        titleMid4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        save2.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_save_48px_1.png")); // NOI18N
        save2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        //action event
        save2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {

                int x=(Integer)idSP1.getValue();
                removePanel.setVisible(false);

                citasDAO.borrarDoctorCitaDB(x);

            }
        });

        idLB1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        idLB1.setText("ID:");

        final javax.swing.GroupLayout removePanelLayout = new javax.swing.GroupLayout(removePanel);
        removePanel.setLayout(removePanelLayout);
        removePanelLayout.setHorizontalGroup(
            removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removePanelLayout.createSequentialGroup()
                .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removePanelLayout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(idLB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(removePanelLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(save2))
                    .addGroup(removePanelLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(titleMid4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        removePanelLayout.setVerticalGroup(
            removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removePanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(titleMid4)
                .addGap(55, 55, 55)
                .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLB1)
                    .addComponent(idSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(save2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        centerPanel.add(removePanel, "card2");

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(upperPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (final javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DoctorWindows().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addLB;
    private javax.swing.JPanel addPanel;
    private javax.swing.JLabel back;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel dateLB;
    private javax.swing.JLabel dateLB1;
    private javax.swing.JTextField dateTF;
    private javax.swing.JTextField dateTF1;
    private javax.swing.JLabel idLB;
    private javax.swing.JLabel idLB1;
    private javax.swing.JSpinner idSP;
    private javax.swing.JSpinner idSP1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel listLB;
    private javax.swing.JPanel listPanel;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JLabel minimizeButton;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JLabel powerButton;
    private javax.swing.JLabel refreshLB;
    private javax.swing.JPanel refreshPanel;
    private javax.swing.JLabel reload;
    private javax.swing.JLabel removeLB;
    private javax.swing.JPanel removePanel;
    private javax.swing.JLabel reportLB;
    private javax.swing.JLabel save;
    private javax.swing.JLabel save1;
    private javax.swing.JLabel save2;
    private javax.swing.JLabel timeLB;
    private javax.swing.JLabel timeLB1;
    private javax.swing.JTextField timeTF;
    private javax.swing.JTextField timeTF1;
    private javax.swing.JLabel titleCentral;
    private javax.swing.JLabel titleMid;
    private javax.swing.JLabel titleMid1;
    private javax.swing.JLabel titleMid2;
    private javax.swing.JLabel titleMid3;
    private javax.swing.JLabel titleMid4;
    private javax.swing.JPanel upperPanel;
    private javax.swing.JLabel whereLB;
    private javax.swing.JLabel whereLB1;
    private javax.swing.JTextField whereTF;
    private javax.swing.JTextField whereTF1;
    private javax.swing.ImageIcon iconFrame;
    // End of variables declaration//GEN-END:variables
}