/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ramon.proyectofinal.utilidades;

import static com.ramon.proyectofinal.Windows.currentDirectory;
import static com.ramon.proyectofinal.modelos.citasDAO.comprobateIdCites;
import com.ramon.proyectofinal.Windows;

import avisos.alert;
import avisos.success;



import javax.swing.table.DefaultTableModel;

import com.ramon.proyectofinal.modelos.citasDAO;
import com.ramon.proyectofinal.modelos.Paciente;
import com.ramon.proyectofinal.modelos.PacienteDAO;
/**
 *
 * @author el_an
 */
public class PatientWindows extends javax.swing.JFrame {

    /**
     * Creates new form PatientWindows
     */
    public PatientWindows() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upperPanel = new javax.swing.JPanel();
        powerButton = new javax.swing.JLabel();
        logoIcon = new javax.swing.JLabel();
        titleCentral = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JLabel();
        centralPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        seeLB = new javax.swing.JLabel();
        addLB = new javax.swing.JLabel();
        urgentLB = new javax.swing.JLabel();
        removeLB = new javax.swing.JLabel();
        iconLB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        seePanel = new javax.swing.JPanel();
        titleMid = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        scrrolPanel = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        reload = new javax.swing.JLabel();
        addPanel = new javax.swing.JPanel();
        titleMid1 = new javax.swing.JLabel();
        nameLB = new javax.swing.JLabel();
        lastNameLB = new javax.swing.JLabel();
        problemLB = new javax.swing.JLabel();
        nameF = new javax.swing.JTextField();
        lastNameF = new javax.swing.JTextField();
        problemF = new javax.swing.JTextField();
        save = new javax.swing.JLabel();
        ageLB = new javax.swing.JLabel();
        statusLB = new javax.swing.JLabel();
        ageSP = new javax.swing.JSpinner();
        idCiteLB = new javax.swing.JLabel();
        idCiteSP = new javax.swing.JSpinner();
        statusF = new javax.swing.JTextField();
        back1 = new javax.swing.JLabel();
        urgentPanel = new javax.swing.JPanel();
        titleMid2 = new javax.swing.JLabel();
        nameLB1 = new javax.swing.JLabel();
        lastNameLB1 = new javax.swing.JLabel();
        problemLB1 = new javax.swing.JLabel();
        nameF1 = new javax.swing.JTextField();
        lastNameF1 = new javax.swing.JTextField();
        problemF1 = new javax.swing.JTextField();
        save1 = new javax.swing.JLabel();
        ageLB1 = new javax.swing.JLabel();
        statusLB1 = new javax.swing.JLabel();
        ageSP1 = new javax.swing.JSpinner();
        jTextField2 = new javax.swing.JTextField();
        back2 = new javax.swing.JLabel();
        removePanel = new javax.swing.JPanel();
        titleMid4 = new javax.swing.JLabel();
        save2 = new javax.swing.JLabel();
        idLB1 = new javax.swing.JLabel();
        idSP1 = new javax.swing.JSpinner();
        back3 = new javax.swing.JLabel();
        currentCitePanel = new javax.swing.JPanel();
        titleMid3 = new javax.swing.JLabel();
        back4 = new javax.swing.JLabel();
        scrrolPanel1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        reload1 = new javax.swing.JLabel();
        iconFrame =new javax.swing.ImageIcon(currentDirectory+"icons8_hospital_sign_55px_1.png");

        setIconImage(iconFrame.getImage());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(729, 444));
        setLocationByPlatform(true);
        setUndecorated(true);

        upperPanel.setBackground(new java.awt.Color(51, 255, 204));
        upperPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        powerButton.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_shutdown_48px.png"));
        powerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        powerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setVisible(false);
                dispose();
                new Windows().setVisible(true);
            }
        });

        logoIcon.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_hospital_48px.png")); // NOI18N

        titleCentral.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleCentral.setText("  Consultorio Medico Central");

        minimizeButton.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_minimize_window_55px.png")); // NOI18N
        minimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setState(PatientWindows.ICONIFIED);

            }
        });

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(minimizeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(powerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(upperPanelLayout.createSequentialGroup()
                        .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(powerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minimizeButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        centralPanel.setBackground(new java.awt.Color(153, 255, 153));
        centralPanel.setLayout(new java.awt.CardLayout());

        menuPanel.setBackground(new java.awt.Color(153, 255, 153));

        seeLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        seeLB.setText("Ver citas Disponibles");
        seeLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                //action event
                seeLB.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        menuPanel.setVisible(false);
                        seePanel.setVisible(true);
        
                    }
                });

        addLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        addLB.setText("Agendar cita");
        addLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                //action event
                addLB.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        menuPanel.setVisible(false);
                        addPanel.setVisible(true);
        
                    }
                });

        urgentLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        urgentLB.setText("Paciente URGENTE");
        urgentLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                        //action event
                        urgentLB.addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(java.awt.event.MouseEvent evt) {
                                menuPanel.setVisible(false);
                                urgentPanel.setVisible(true);
                
                            }
                        });

        removeLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        removeLB.setText("Borrar cita");
        removeLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                        //action event
                        removeLB.addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(java.awt.event.MouseEvent evt) {
                                menuPanel.setVisible(false);
                                removePanel.setVisible(true);
                
                            }
                        });

        iconLB.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_user_100px.png")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Ver Paciente en Citas");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                        //action event
                        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(java.awt.event.MouseEvent evt) {
                                menuPanel.setVisible(false);
                                currentCitePanel.setVisible(true);
                
                            }
                        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seeLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(urgentLB)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconLB)
                .addGap(329, 329, 329))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(addLB)
                        .addGap(107, 107, 107)
                        .addComponent(removeLB))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel1)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seeLB)
                    .addComponent(urgentLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(addLB)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(removeLB)
                        .addGap(18, 18, 18)))
                .addComponent(iconLB)
                .addGap(27, 27, 27))
        );

        centralPanel.add(menuPanel, "card7");

        seePanel.setBackground(new java.awt.Color(153, 255, 153));

        titleMid.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleMid.setForeground(new java.awt.Color(255, 255, 255));
        titleMid.setText("Listado de citas");
        titleMid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        back.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_back_48px.png")); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                                //action event
                                back.addMouseListener(new java.awt.event.MouseAdapter() {
                                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                                        seePanel.setVisible(false);
                                        menuPanel.setVisible(true);
                        
                                    }
                                });

        //table an rows
        String[]columns= {"id_cita", "Fecha", "Hora", "Lugar","id_doctor","created","modified"};
        DefaultTableModel modelo= new DefaultTableModel(null,columns);
        jTable1.setModel(modelo);
        citasDAO.listarDoctorCitasDB(modelo,"patient");
        
        scrrolPanel.setViewportView(jTable1);

        reload.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_process_48px_1.png")); // NOI18N
        reload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                                //action event
                                reload.addMouseListener(new java.awt.event.MouseAdapter() {
                                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                                        DefaultTableModel modelo= new DefaultTableModel(null,columns);
                                        jTable1.setModel(modelo);
                                        citasDAO.listarDoctorCitasDB(modelo,"patient");
                        
                                    }
                                });

        javax.swing.GroupLayout seePanelLayout = new javax.swing.GroupLayout(seePanel);
        seePanel.setLayout(seePanelLayout);
        seePanelLayout.setHorizontalGroup(
            seePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seePanelLayout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addGroup(seePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seePanelLayout.createSequentialGroup()
                        .addComponent(titleMid)
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seePanelLayout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(40, 40, 40)
                        .addComponent(reload)
                        .addGap(277, 277, 277))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrrolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        seePanelLayout.setVerticalGroup(
            seePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(titleMid)
                .addGap(12, 12, 12)
                .addComponent(scrrolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(back)
                    .addComponent(reload))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        centralPanel.add(seePanel, "card3");

        addPanel.setBackground(new java.awt.Color(153, 255, 153));

        titleMid1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleMid1.setForeground(new java.awt.Color(255, 255, 255));
        titleMid1.setText("Agregando una Cita");
        titleMid1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nameLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nameLB.setText("Nombre:");
        nameLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lastNameLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lastNameLB.setText("Apellido:");
        lastNameLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        problemLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        problemLB.setText("Molestia:");
        problemLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nameF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N


        lastNameF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        problemF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N


        save.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_save_48px_1.png")); // NOI18N
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                        //action event
                        save.addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(java.awt.event.MouseEvent evt) {
        
                                Paciente datos= new Paciente();
                                
                                datos.setName(nameF.getText());
                                datos.setLastName(lastNameF.getText());
                                datos.setAge((Integer)ageSP.getValue());
                                datos.setStatus(statusF.getText());
                                datos.setProblem(problemF.getText());

                                int x=(Integer)idCiteSP.getValue();


        
                                if(datos.getName().isEmpty()||datos.getLastName().isEmpty()||datos.getProblem().isEmpty()||
                                datos.getStatus().isEmpty() || !comprobateIdCites.contains(x)){
                                    new alert("isEmpty").setVisible(true);
        
                                }
        
                                else{
                                    PacienteDAO.crearPacienteDB(datos, x);
                                    PacienteDAO.borrarCitaDisponibleDB(x);
                                    addPanel.setVisible(false);
        
                                    new success("save").setVisible(true);
                                }
                
                            }
                        });

        ageLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ageLB.setText("Edad:");

        statusLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        statusLB.setText("Estado de Salud:");

        ageSP.setFont(new java.awt.Font("Arial", 1, 9)); // NOI18N

        idCiteLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        idCiteLB.setText("ID de CITA:");

        idCiteSP.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        statusF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N


        back1.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_back_48px.png")); // NOI18N
        back1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                //action event
                back1.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        addPanel.setVisible(false);
                        menuPanel.setVisible(true);
        
                    }
                });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addComponent(titleMid1)
                .addGap(246, 246, 246))
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addPanelLayout.createSequentialGroup()
                                        .addComponent(nameLB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nameF, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(addPanelLayout.createSequentialGroup()
                                        .addComponent(problemLB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(problemF, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addPanelLayout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(ageLB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ageSP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(addPanelLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(idCiteLB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(idCiteSP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(lastNameLB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameF, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(statusLB)
                                .addGap(18, 18, 18)
                                .addComponent(statusF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(back1)
                        .addGap(18, 18, 18)
                        .addComponent(save)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(titleMid1)
                .addGap(37, 37, 37)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLB)
                            .addComponent(nameF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageSP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLB)
                            .addComponent(lastNameF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(ageLB)
                        .addGap(31, 31, 31)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusLB)
                            .addComponent(statusF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(problemF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idCiteLB)
                    .addComponent(idCiteSP)
                    .addComponent(problemLB))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(save)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                        .addComponent(back1)
                        .addGap(24, 24, 24))))
        );

        centralPanel.add(addPanel, "card2");

        urgentPanel.setBackground(new java.awt.Color(153, 255, 153));

        titleMid2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleMid2.setForeground(new java.awt.Color(255, 255, 255));
        titleMid2.setText("Agregando una Cita URGENTE");
        titleMid2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nameLB1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nameLB1.setText("Nombre:");
        nameLB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lastNameLB1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lastNameLB1.setText("Apellido:");
        lastNameLB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        problemLB1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        problemLB1.setText("Molestia:");
        problemLB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nameF1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N


        lastNameF1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        problemF1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N


        save1.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_save_48px_1.png")); // NOI18N
        save1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                        //action event
                        save1.addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(java.awt.event.MouseEvent evt) {
        
                                Paciente datos= new Paciente();
                                
                                datos.setName(nameF.getText());
                                datos.setLastName(lastNameF.getText());
                                datos.setAge((Integer)ageSP.getValue());
                                datos.setStatus(statusF.getText());
                                datos.setProblem(problemF.getText());



        
                                if(datos.getName().isEmpty()||datos.getLastName().isEmpty()||datos.getProblem().isEmpty()||
                                datos.getStatus().isEmpty()){
                                    new alert("isEmpty").setVisible(true);
        
                                }
        
                                else{
                                    PacienteDAO.crearPacienteUrgenteDB(datos);
                                    urgentPanel.setVisible(false);
        
                                    new success("save").setVisible(true);
                                }
                
                            }
                        });

        ageLB1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ageLB1.setText("Edad:");

        statusLB1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        statusLB1.setText("Estado de Salud:");

        ageSP1.setFont(new java.awt.Font("Arial", 1, 9)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        back2.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_back_48px.png")); // NOI18N
        back2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                        //action event
                        back1.addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(java.awt.event.MouseEvent evt) {
                                urgentPanel.setVisible(false);
                                menuPanel.setVisible(true);
                
                            }
                        });

        javax.swing.GroupLayout urgentPanelLayout = new javax.swing.GroupLayout(urgentPanel);
        urgentPanel.setLayout(urgentPanelLayout);
        urgentPanelLayout.setHorizontalGroup(
            urgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(urgentPanelLayout.createSequentialGroup()
                .addGroup(urgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(urgentPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(urgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(urgentPanelLayout.createSequentialGroup()
                                .addComponent(lastNameLB1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameF1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(statusLB1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(urgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(titleMid2)
                                .addGroup(urgentPanelLayout.createSequentialGroup()
                                    .addGroup(urgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(urgentPanelLayout.createSequentialGroup()
                                            .addComponent(nameLB1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nameF1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(urgentPanelLayout.createSequentialGroup()
                                            .addComponent(problemLB1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(problemF1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(59, 59, 59)
                                    .addComponent(ageLB1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ageSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(urgentPanelLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(back2)
                        .addGap(18, 18, 18)
                        .addComponent(save1)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        urgentPanelLayout.setVerticalGroup(
            urgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(urgentPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(titleMid2)
                .addGap(41, 41, 41)
                .addGroup(urgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(urgentPanelLayout.createSequentialGroup()
                        .addGroup(urgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLB1)
                            .addComponent(nameF1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(urgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLB1)
                            .addComponent(lastNameF1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(urgentPanelLayout.createSequentialGroup()
                        .addComponent(ageLB1)
                        .addGap(31, 31, 31)
                        .addGroup(urgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusLB1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(urgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(problemF1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(problemLB1))
                .addGap(18, 18, 18)
                .addGroup(urgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(urgentPanelLayout.createSequentialGroup()
                        .addComponent(save1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, urgentPanelLayout.createSequentialGroup()
                        .addComponent(back2)
                        .addGap(24, 24, 24))))
        );

        centralPanel.add(urgentPanel, "card2");

        removePanel.setBackground(new java.awt.Color(153, 255, 153));

        titleMid4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleMid4.setForeground(new java.awt.Color(255, 255, 255));
        titleMid4.setText("Borrar cita (No Urgente)");
        titleMid4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        save2.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_save_48px_1.png")); // NOI18N
        save2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                                //action event
                                save2.addMouseListener(new java.awt.event.MouseAdapter() {
                                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                                        int x=(Integer)idSP1.getValue();
                                        removePanel.setVisible(false);
                        
                                        PacienteDAO.borrarCitaDB(x);
                        
                                    }
                                });

        idLB1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        idLB1.setText("ID:");

        back3.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_back_48px.png")); // NOI18N
        back3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                                //action event
                                back3.addMouseListener(new java.awt.event.MouseAdapter() {
                                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                                        removePanel.setVisible(false);
                                        menuPanel.setVisible(true);
                        
                                    }
                                });

        javax.swing.GroupLayout removePanelLayout = new javax.swing.GroupLayout(removePanel);
        removePanel.setLayout(removePanelLayout);
        removePanelLayout.setHorizontalGroup(
            removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removePanelLayout.createSequentialGroup()
                .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removePanelLayout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(idLB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(removePanelLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(back3)
                        .addGap(18, 18, 18)
                        .addComponent(save2))
                    .addGroup(removePanelLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(titleMid4)))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        removePanelLayout.setVerticalGroup(
            removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removePanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(titleMid4)
                .addGap(53, 53, 53)
                .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLB1)
                    .addComponent(idSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back3)
                    .addComponent(save2))
                .addGap(31, 31, 31))
        );

        centralPanel.add(removePanel, "card2");

        currentCitePanel.setBackground(new java.awt.Color(153, 255, 153));

        titleMid3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleMid3.setForeground(new java.awt.Color(255, 255, 255));
        titleMid3.setText("Listado de citas");
        titleMid3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        back4.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_back_48px.png")); // NOI18N
        back4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                                       //action event
                                       back4.addMouseListener(new java.awt.event.MouseAdapter() {
                                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                            currentCitePanel.setVisible(false);
                                            menuPanel.setVisible(true);
                            
                                        }
                                    });

        //table an rows
        String[]columns1= {"id_cita", "Nombre", "Apellido", "edad","estado","problema","id_doctor"};
        DefaultTableModel modelo1= new DefaultTableModel(null,columns1);
        jTable2.setModel(modelo1);
        PacienteDAO.listarCitasDB(modelo1);
        
        scrrolPanel1.setViewportView(jTable2);

        reload1.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_process_48px_1.png")); // NOI18N
        reload1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                               //action event
                                reload1.addMouseListener(new java.awt.event.MouseAdapter() {
                                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                                        DefaultTableModel modelo1= new DefaultTableModel(null,columns1);
                                        jTable2.setModel(modelo1);
                                        PacienteDAO.listarCitasDB(modelo1);
                        
                                    }
                                }); 

        javax.swing.GroupLayout currentCitePanelLayout = new javax.swing.GroupLayout(currentCitePanel);
        currentCitePanel.setLayout(currentCitePanelLayout);
        currentCitePanelLayout.setHorizontalGroup(
            currentCitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentCitePanelLayout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addGroup(currentCitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, currentCitePanelLayout.createSequentialGroup()
                        .addComponent(titleMid3)
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, currentCitePanelLayout.createSequentialGroup()
                        .addComponent(back4)
                        .addGap(40, 40, 40)
                        .addComponent(reload1)
                        .addGap(277, 277, 277))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, currentCitePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrrolPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        currentCitePanelLayout.setVerticalGroup(
            currentCitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentCitePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(titleMid3)
                .addGap(12, 12, 12)
                .addComponent(scrrolPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(currentCitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(back4)
                    .addComponent(reload1))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        centralPanel.add(currentCitePanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(upperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(centralPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(centralPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientWindows().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addLB;
    private javax.swing.JPanel addPanel;
    private javax.swing.JLabel ageLB;
    private javax.swing.JLabel ageLB1;
    private javax.swing.JSpinner ageSP;
    private javax.swing.JSpinner ageSP1;
    private javax.swing.JLabel back;
    private javax.swing.JLabel back1;
    private javax.swing.JLabel back2;
    private javax.swing.JLabel back3;
    private javax.swing.JLabel back4;
    private javax.swing.JPanel centralPanel;
    private javax.swing.JPanel currentCitePanel;
    private javax.swing.JLabel iconLB;
    private javax.swing.JLabel idCiteLB;
    private javax.swing.JSpinner idCiteSP;
    private javax.swing.JLabel idLB1;
    private javax.swing.JSpinner idSP1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField lastNameF;
    private javax.swing.JTextField lastNameF1;
    private javax.swing.JLabel lastNameLB;
    private javax.swing.JLabel lastNameLB1;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel minimizeButton;
    private javax.swing.JTextField nameF;
    private javax.swing.JTextField nameF1;
    private javax.swing.JLabel nameLB;
    private javax.swing.JLabel nameLB1;
    private javax.swing.JLabel powerButton;
    private javax.swing.JTextField problemF;
    private javax.swing.JTextField problemF1;
    private javax.swing.JLabel problemLB;
    private javax.swing.JLabel problemLB1;
    private javax.swing.JLabel reload;
    private javax.swing.JLabel reload1;
    private javax.swing.JLabel removeLB;
    private javax.swing.JPanel removePanel;
    private javax.swing.JLabel save;
    private javax.swing.JLabel save1;
    private javax.swing.JLabel save2;
    private javax.swing.JScrollPane scrrolPanel;
    private javax.swing.JScrollPane scrrolPanel1;
    private javax.swing.JLabel seeLB;
    private javax.swing.JPanel seePanel;
    private javax.swing.JTextField statusF;
    private javax.swing.JLabel statusLB;
    private javax.swing.JLabel statusLB1;
    private javax.swing.JLabel titleCentral;
    private javax.swing.JLabel titleMid;
    private javax.swing.JLabel titleMid1;
    private javax.swing.JLabel titleMid2;
    private javax.swing.JLabel titleMid3;
    private javax.swing.JLabel titleMid4;
    private javax.swing.JPanel upperPanel;
    private javax.swing.JLabel urgentLB;
    private javax.swing.JPanel urgentPanel;
    private javax.swing.ImageIcon iconFrame;

    // End of variables declaration//GEN-END:variables
}
