/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ramon.proyectofinal.utilidades;
import static com.ramon.proyectofinal.Windows.currentDirectory;
import static com.ramon.proyectofinal.modelos.DoctorDAO.doctorName;
import javax.swing.table.DefaultTableModel;

import com.ramon.proyectofinal.LoginWindows;
import com.ramon.proyectofinal.modelos.ReportDAO;
/**
 *
 * @author el_an
 */
public class ReportDoctor extends javax.swing.JFrame {

    /**
     * Creates new form ReportDoctor
     */
    public ReportDoctor() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upperPanel = new javax.swing.JPanel();
        powerButton = new javax.swing.JLabel();
        logoIcon = new javax.swing.JLabel();
        titleCentral = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        midTitle = new javax.swing.JLabel();
        urgTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        back = new javax.swing.JLabel();
        reload = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        upperPanel.setBackground(new java.awt.Color(51, 255, 204));
        upperPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        powerButton.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_shutdown_48px.png")); // NOI18N
        powerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        powerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setVisible(false);
                dispose(); 
                new LoginWindows().setVisible(true);

            }
        });

        logoIcon.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_hospital_48px.png")); // NOI18N

        titleCentral.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleCentral.setText("  Consultorio del Doctor "+doctorName);

        minimizeButton.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_minimize_window_55px.png")); // NOI18N
        minimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setState(ReportDoctor.ICONIFIED);

            }
        });

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(minimizeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(powerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(upperPanelLayout.createSequentialGroup()
                        .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(powerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minimizeButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        centerPanel.setBackground(new java.awt.Color(153, 255, 153));

        midTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        midTitle.setText("Pacientes con Cita");

        urgTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        urgTitle.setText("Pacientes URGENTES");

        //table an rows
        String[]columns= {"Nombre", "Apellido", "edad","estado","problema","id_doctor"};
        DefaultTableModel modelo= new DefaultTableModel(null,columns);
        jTable1.setModel(modelo);
        ReportDAO.listarPacienteDB(modelo);
        
        jScrollPane1.setViewportView(jTable1);

        //table an rows
        String[]columns1= {"Nombre", "Apellido", "edad","estado","problema"};
        DefaultTableModel modelo1= new DefaultTableModel(null,columns1);
        jTable2.setModel(modelo1);
        ReportDAO.listarPacienteUrgenteDB(modelo1);

        jScrollPane2.setViewportView(jTable2);

        back.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_back_48px.png")); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setVisible(false);
                dispose(); 
                new LoginWindows().setVisible(true);
            }
        });
        

        reload.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_process_48px_1.png")); // NOI18N
        reload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                                        //action event
                                        reload.addMouseListener(new java.awt.event.MouseAdapter() {
                                            public void mouseClicked(java.awt.event.MouseEvent evt) {
                                                DefaultTableModel modelo= new DefaultTableModel(null,columns);
                                                jTable1.setModel(modelo);
                                                ReportDAO.listarPacienteDB(modelo);

                                                DefaultTableModel modelo1= new DefaultTableModel(null,columns1);
                                                jTable2.setModel(modelo1);
                                                ReportDAO.listarPacienteUrgenteDB(modelo1);
                                
                                            }
                                        });

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(urgTitle))
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(midTitle))
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(back)
                        .addGap(43, 43, 43)
                        .addComponent(reload)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(midTitle)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(urgTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(reload))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(upperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //GEN-LAST:event_minimizeButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JLabel midTitle;
    private javax.swing.JLabel minimizeButton;
    private javax.swing.JLabel powerButton;
    private javax.swing.JLabel reload;
    private javax.swing.JLabel titleCentral;
    private javax.swing.JPanel upperPanel;
    private javax.swing.JLabel urgTitle;
    // End of variables declaration//GEN-END:variables
}
