/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ramon.proyectofinal;
import java.util.Arrays;

import static com.ramon.proyectofinal.Windows.currentDirectory;
import com.ramon.proyectofinal.modelos.Doctor;
import com.ramon.proyectofinal.modelos.DoctorDAO;

import avisos.*;

/**
 *
 * @author el_an
 */
public class RegistreWindows extends javax.swing.JFrame {

    /**
     * Creates new form RegistreWindows
     */
    public RegistreWindows() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upperPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JLabel();
        upperTitle = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        personalInformation = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        lastName = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        especiality = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        sexC = new javax.swing.JComboBox<>();
        lastNameTF = new javax.swing.JTextField();
        ageSp = new javax.swing.JSpinner();
        especialityTF = new javax.swing.JTextField();
        next = new javax.swing.JLabel();
        otherInformation = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        password1 = new javax.swing.JLabel();
        password2 = new javax.swing.JLabel();
        save = new javax.swing.JLabel();
        userTF = new javax.swing.JTextField();
        password1F = new javax.swing.JPasswordField();
        password2F = new javax.swing.JPasswordField();
        back = new javax.swing.JLabel();
        iconFrame =new javax.swing.ImageIcon(currentDirectory+"icons8_hospital_sign_55px_1.png");

        setIconImage(iconFrame.getImage());
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        upperPanel.setBackground(new java.awt.Color(51, 255, 204));

        closeButton.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_close_window_48px.png")); // NOI18N
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                        //Action after mouse clicked
                        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                                setVisible(false);
                                dispose(); 
                                new LoginWindows().setVisible(true);
        
                            }
                        });

        upperTitle.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        upperTitle.setText("Datos");

        final javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(upperTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(closeButton)
                .addContainerGap())
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upperTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeButton))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        centerPanel.setLayout(new java.awt.CardLayout());

        personalInformation.setBackground(new java.awt.Color(153, 255, 153));

        name.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        name.setText("Nombres:");

        lastName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lastName.setText("Apellidos");

        age.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        age.setText("Edad:");

        especiality.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        especiality.setText("Especialidad:");

        sex.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        sex.setText("Sexo:");

        nameTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        sexC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sexC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer", "Otro", "No especificar" }));

    
        lastNameTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        ageSp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        especialityTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        next.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_chevron_right_48px.png")); // NOI18N
        next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                        //Action after mouse clicked
                        next.addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                                personalInformation.setVisible(false);
                                otherInformation.setVisible(true);
        
                            }
                        });

        final javax.swing.GroupLayout personalInformationLayout = new javax.swing.GroupLayout(personalInformation);
        personalInformation.setLayout(personalInformationLayout);
        personalInformationLayout.setHorizontalGroup(
            personalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInformationLayout.createSequentialGroup()
                .addGroup(personalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalInformationLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(personalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(personalInformationLayout.createSequentialGroup()
                                    .addComponent(sex)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(sexC, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(personalInformationLayout.createSequentialGroup()
                                    .addComponent(name)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(personalInformationLayout.createSequentialGroup()
                                    .addComponent(lastName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lastNameTF))
                                .addGroup(personalInformationLayout.createSequentialGroup()
                                    .addComponent(age)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ageSp, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(personalInformationLayout.createSequentialGroup()
                                .addComponent(especiality)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(especialityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(personalInformationLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(next)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        personalInformationLayout.setVerticalGroup(
            personalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInformationLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(personalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastNameTF))
                .addGap(33, 33, 33)
                .addGroup(personalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age)
                    .addComponent(ageSp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(personalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(especiality)
                    .addComponent(especialityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sexC))
                .addGap(18, 18, 18)
                .addComponent(next)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        centerPanel.add(personalInformation, "card2");

        otherInformation.setBackground(new java.awt.Color(153, 255, 153));

        username.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        username.setText("Cedula o DNI:");

        password1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        password1.setText("Contraseña:");

        password2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        password2.setText("Contraseña:");

        save.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_save_48px_1.png")); // NOI18N
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                                //Action after mouse clicked
                                save.addMouseListener(new java.awt.event.MouseAdapter() {
                                    public void mouseClicked(final java.awt.event.MouseEvent evt) {
                                        Doctor datos= new Doctor();
                                        datos.setName(nameTF.getText());
                                        datos.setLastName(lastNameTF.getText());
                                        datos.setAge((Integer)ageSp.getValue());
                                        datos.setEspeciality(especialityTF.getText());
                                        datos.setSex(sexC.getSelectedItem().toString());
                                        datos.setUser(userTF.getText());
                                        datos.setPassword(String.valueOf(password2F.getPassword()));

                                        char[] a = password1F.getPassword();
                                        char[] b = password2F.getPassword();

                                        if(datos.getName().isEmpty()||datos.getLastName().isEmpty()||datos.getEspeciality().isEmpty()||datos.getUser().isEmpty()||datos.getPassword().isEmpty()){
                                            new alert("isEmpty").setVisible(true);
                                            
                                        }

                                        else if(Arrays.equals(a,b)&& a.length>1){
                                            DoctorDAO.crearDoctorDB(datos);
                                            setVisible(false);
                                            dispose(); 
                                            new success("save").setVisible(true);
                                        }
                                        else if(!Arrays.equals(a,b)){
                                            new alert("passwordError").setVisible(true);
                                        }
                                    }
                                });

        back.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_back_48px.png")); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); 
                        //Action after mouse clicked
                        back.addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(final java.awt.event.MouseEvent evt) {
                                otherInformation.setVisible(false);
                                personalInformation.setVisible(true);
        
                            }
                        });

        final javax.swing.GroupLayout otherInformationLayout = new javax.swing.GroupLayout(otherInformation);
        otherInformation.setLayout(otherInformationLayout);
        otherInformationLayout.setHorizontalGroup(
            otherInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherInformationLayout.createSequentialGroup()
                .addGroup(otherInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(otherInformationLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(otherInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(otherInformationLayout.createSequentialGroup()
                                .addComponent(password2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(password2F))
                            .addGroup(otherInformationLayout.createSequentialGroup()
                                .addComponent(password1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(password1F))
                            .addGroup(otherInformationLayout.createSequentialGroup()
                                .addComponent(username)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(userTF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(otherInformationLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(back)
                        .addGap(53, 53, 53)
                        .addComponent(save)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        otherInformationLayout.setVerticalGroup(
            otherInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherInformationLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(otherInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username)
                    .addComponent(userTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(otherInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password1)
                    .addComponent(password1F, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(otherInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password2)
                    .addComponent(password2F, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(otherInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back)
                    .addComponent(save))
                .addGap(71, 71, 71))
        );

        centerPanel.add(otherInformation, "card3");

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(upperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (final javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (final ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistreWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (final InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistreWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (final IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistreWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (final javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistreWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistreWindows().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JSpinner ageSp;
    private javax.swing.JLabel back;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel closeButton;
    private javax.swing.JLabel especiality;
    private javax.swing.JTextField especialityTF;
    private javax.swing.JLabel lastName;
    private javax.swing.JTextField lastNameTF;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel next;
    private javax.swing.JPanel otherInformation;
    private javax.swing.JLabel password1;
    private javax.swing.JPasswordField password1F;
    private javax.swing.JLabel password2;
    private javax.swing.JPasswordField password2F;
    private javax.swing.JPanel personalInformation;
    private javax.swing.JLabel save;
    private javax.swing.JLabel sex;
    private javax.swing.JComboBox<String> sexC;
    private javax.swing.JPanel upperPanel;
    private javax.swing.JLabel upperTitle;
    private javax.swing.JTextField userTF;
    private javax.swing.JLabel username;
    private javax.swing.ImageIcon iconFrame;
    // End of variables declaration//GEN-END:variables
}
