/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ramon.proyectofinal;
import com.ramon.proyectofinal.utilidades.PatientWindows;

/**
 *
 * @author el_an
 */
public class Windows extends javax.swing.JFrame {
    
    //image location
    public static final String currentDirectory = System.getProperty("user.dir")+"\\src\\main\\java\\com\\ramon\\proyectofinal\\img\\";


    /**
     * Creates new form Windows
     */
    public Windows() {
        initComponents();
        setLocationRelativeTo(null);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upperPanel = new javax.swing.JPanel();
        powerButton = new javax.swing.JLabel();
        logoIcon = new javax.swing.JLabel();
        titleCentral = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        titleMidCenter = new javax.swing.JLabel();
        pacientIcon = new javax.swing.JLabel();
        doctorIcon = new javax.swing.JLabel();
        pacientText = new javax.swing.JLabel();
        doctorText = new javax.swing.JLabel();
        arrows = new javax.swing.JLabel();
        iconFrame =new javax.swing.ImageIcon(currentDirectory+"icons8_hospital_sign_55px_1.png");

        setIconImage(iconFrame.getImage());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Final");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(50, 100));
        setLocationByPlatform(true);
        setUndecorated(true);


        upperPanel.setBackground(new java.awt.Color(51, 255, 204));
        upperPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        powerButton.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_shutdown_48px.png")); // NOI18N
        powerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        powerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                System.exit(0);
            }
        });

        logoIcon.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_hospital_48px.png")); // NOI18N

        titleCentral.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleCentral.setText("  Consultorio Medico para Doctores");

        minimizeButton.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_minimize_window_55px.png")); // NOI18N
        minimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setState(Windows.ICONIFIED);
            }
        });

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(titleCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(minimizeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(powerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(upperPanelLayout.createSequentialGroup()
                        .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(powerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minimizeButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        centerPanel.setBackground(new java.awt.Color(153, 255, 153));
        centerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        titleMidCenter.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleMidCenter.setText("Ingresar como:");

        pacientIcon.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_user_100px.png")); // NOI18N
        pacientIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pacientIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setVisible(false);
                dispose(); 
                new PatientWindows().setVisible(true);
            }
        });


        doctorIcon.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_medical_doctor_100px.png")); // NOI18N
        doctorIcon.setText("jLabel6");
        doctorIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doctorIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setVisible(false);
                dispose(); 
                new LoginWindows().setVisible(true);
            }
        });

        pacientText.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        pacientText.setText("Paciente");

        doctorText.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        doctorText.setText("Doctor");

        arrows.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        arrows.setText("<------------------->");

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(pacientText)
                        .addGap(218, 218, 218)
                        .addComponent(doctorText))
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(pacientIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleMidCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arrows))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doctorIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pacientIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doctorIcon)
                        .addComponent(arrows))
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(titleMidCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorText)
                    .addComponent(pacientText, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(upperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(centerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Windows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                new Windows().setVisible(true);               
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrows;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel doctorIcon;
    private javax.swing.JLabel doctorText;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JLabel minimizeButton;
    private javax.swing.JLabel pacientIcon;
    private javax.swing.JLabel pacientText;
    private javax.swing.JLabel powerButton;
    private javax.swing.JLabel titleCentral;
    private javax.swing.JLabel titleMidCenter;
    private javax.swing.JPanel upperPanel;
    private javax.swing.ImageIcon iconFrame;
    // End of variables declaration//GEN-END:variables
}
