/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package avisos;
import static com.ramon.proyectofinal.Windows.currentDirectory;
/**
 *
 * @author el_an
 */
public class alert extends javax.swing.JFrame {

    /**
     * Creates new form alert
     */
    public alert(String typeOperation) {
        initComponents(typeOperation);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String typeOperation) {

        upperPanel = new javax.swing.JPanel();
        alert = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        passwordPanel = new javax.swing.JPanel();
        message = new javax.swing.JLabel();
        warningIcon = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        dataPanel = new javax.swing.JPanel();
        message1 = new javax.swing.JLabel();
        close1 = new javax.swing.JLabel();
        warningIcon1 = new javax.swing.JLabel();
        isEmptyPanel = new javax.swing.JPanel();
        message2 = new javax.swing.JLabel();
        warningIcon2 = new javax.swing.JLabel();
        close2 = new javax.swing.JLabel();
        iconFrame =new javax.swing.ImageIcon(currentDirectory+"icons8_error_48px_1.png");

        setIconImage(iconFrame.getImage());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(50, 100));
        setLocationByPlatform(true);
        setUndecorated(true);
        upperPanel.setBackground(new java.awt.Color(153, 153, 255));

        alert.setBackground(new java.awt.Color(255, 0, 0));
        alert.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        alert.setForeground(new java.awt.Color(204, 204, 0));
        alert.setText("Alerta!");

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(alert, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(alert)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        centerPanel.setLayout(new java.awt.CardLayout());
        if(typeOperation=="passwordError"){
            passwordPanel.setBackground(new java.awt.Color(51, 255, 204));

            message.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
            message.setText("Las Contraseña no Coinciden...");

            warningIcon.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_error_48px_1.png")); // NOI18N

            close.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_close_window_48px.png")); // NOI18N
            close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                                    //Action after mouse clicked
                                    close.addMouseListener(new java.awt.event.MouseAdapter() {
                                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                            setVisible(false);
                    
                                        }
                                    }); 
            javax.swing.GroupLayout passwordPanelLayout = new javax.swing.GroupLayout(passwordPanel);
            passwordPanel.setLayout(passwordPanelLayout);
            passwordPanelLayout.setHorizontalGroup(
                passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(passwordPanelLayout.createSequentialGroup()
                    .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(passwordPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(passwordPanelLayout.createSequentialGroup()
                            .addGap(167, 167, 167)
                            .addComponent(warningIcon))
                        .addGroup(passwordPanelLayout.createSequentialGroup()
                            .addGap(172, 172, 172)
                            .addComponent(close)))
                    .addContainerGap(18, Short.MAX_VALUE))
            );
            passwordPanelLayout.setVerticalGroup(
                passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(passwordPanelLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(warningIcon)
                    .addGap(44, 44, 44)
                    .addComponent(message)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(close)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            centerPanel.add(passwordPanel, "card2");
        }
        if(typeOperation=="dataError"){                            
            dataPanel.setBackground(new java.awt.Color(51, 255, 204));

            message1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
            message1.setText("Datos incorrectos..");

            close1.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_close_window_48px.png")); // NOI18N
            close1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                                            //Action after mouse clicked
                                            close1.addMouseListener(new java.awt.event.MouseAdapter() {
                                                public void mouseClicked(java.awt.event.MouseEvent evt) {
                                                    setVisible(false);
                            
                                                }
                                            }); 
            warningIcon1.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_error_48px_1.png")); // NOI18N

            javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
            dataPanel.setLayout(dataPanelLayout);
            dataPanelLayout.setHorizontalGroup(
                dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataPanelLayout.createSequentialGroup()
                    .addGap(176, 176, 176)
                    .addComponent(warningIcon1)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPanelLayout.createSequentialGroup()
                    .addContainerGap(90, Short.MAX_VALUE)
                    .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPanelLayout.createSequentialGroup()
                            .addComponent(close1)
                            .addGap(174, 174, 174))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPanelLayout.createSequentialGroup()
                            .addComponent(message1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(81, 81, 81))))
            );
            dataPanelLayout.setVerticalGroup(
                dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataPanelLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(warningIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(message1)
                    .addGap(18, 18, 18)
                    .addComponent(close1)
                    .addContainerGap(34, Short.MAX_VALUE))
            );

            centerPanel.add(dataPanel, "card3");
        }                 
        if(typeOperation=="isEmpty"){                 
            isEmptyPanel.setBackground(new java.awt.Color(51, 255, 204));

            message2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
            message2.setText("Favor rellenar los campos vacios");

            warningIcon2.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_error_48px_1.png")); // NOI18N

            close2.setIcon(new javax.swing.ImageIcon(currentDirectory+"icons8_close_window_48px.png")); // NOI18N
            close2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                                            //Action after mouse clicked
                                            close2.addMouseListener(new java.awt.event.MouseAdapter() {
                                                public void mouseClicked(java.awt.event.MouseEvent evt) {
                                                    setVisible(false);
                            
                                                }
                                            }); 

            javax.swing.GroupLayout isEmptyPanelLayout = new javax.swing.GroupLayout(isEmptyPanel);
            isEmptyPanel.setLayout(isEmptyPanelLayout);
            isEmptyPanelLayout.setHorizontalGroup(
                isEmptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(isEmptyPanelLayout.createSequentialGroup()
                    .addGap(169, 169, 169)
                    .addGroup(isEmptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(close2)
                        .addComponent(warningIcon2))
                    .addContainerGap(183, Short.MAX_VALUE))
                .addGroup(isEmptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(isEmptyPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(message2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE)))
            );
            isEmptyPanelLayout.setVerticalGroup(
                isEmptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(isEmptyPanelLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(warningIcon2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                    .addComponent(close2)
                    .addGap(31, 31, 31))
                .addGroup(isEmptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(isEmptyPanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(message2)
                        .addContainerGap(94, Short.MAX_VALUE)))
            );

            centerPanel.add(isEmptyPanel, "card4");
        }                                    
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(upperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alert("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel close;
    private javax.swing.JLabel close1;
    private javax.swing.JLabel close2;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JPanel isEmptyPanel;
    private javax.swing.JLabel message;
    private javax.swing.JLabel message1;
    private javax.swing.JLabel message2;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JPanel upperPanel;
    private javax.swing.JLabel warningIcon;
    private javax.swing.JLabel warningIcon1;
    private javax.swing.JLabel warningIcon2;
    private javax.swing.ImageIcon iconFrame;

    // End of variables declaration//GEN-END:variables
}
